; ./.-class-table.lisp
; Automatically generated by jvm2acl2x on Thu Jan 09 13:21:09 CST 2003.
;

;; load all class description as Lisp constants
(ld "*com.sun.cldc.i18n.StreamReader*.lisp")
(ld "*com.sun.cldc.i18n.StreamWriter*.lisp")
(ld "*com.sun.cldc.i18n.uclc.DefaultCaseConverter*.lisp")
(ld "*com.sun.cldc.i18n.Helper*.lisp")
(ld "*com.sun.cldc.i18n.j2me.ISO8859_1_Reader*.lisp")
(ld "*com.sun.cldc.i18n.j2me.ISO8859_1_Writer*.lisp")
(ld "*com.sun.cldc.i18n.j2se.Default_Writer*.lisp")
(ld "*com.sun.cldc.io.DateParser*.lisp")
(ld "*com.sun.cldc.io.ConnectionBaseInterface*.lisp")
(ld "*com.sun.cldc.io.GeneralBase*.lisp")
(ld "*com.sun.cldc.io.ConnectionBase*.lisp")
(ld "*com.sun.cldc.io.NetworkConnectionBase*.lisp")
(ld "*com.sun.cldc.io.connections.HttpConnection*.lisp")
(ld "*com.sun.cldc.io.j2me.comm.Protocol*.lisp")
(ld "*com.sun.cldc.io.j2me.comm.PrivateInputStream*.lisp")
(ld "*com.sun.cldc.io.j2me.comm.PrivateInputStreamWithBuffer*.lisp")
(ld "*com.sun.cldc.io.j2me.comm.PrivateOutputStream*.lisp")
(ld "*com.sun.cldc.io.j2me.datagram.DatagramObject*.lisp")
(ld "*com.sun.cldc.io.j2me.datagram.Protocol*.lisp")
(ld "*com.sun.cldc.io.j2me.debug.Protocol*.lisp")
(ld "*com.sun.cldc.io.j2me.debug.PrivateOutputStream*.lisp")
(ld "*com.sun.cldc.io.j2me.events.Protocol*.lisp")
(ld "*com.sun.cldc.io.j2me.events.PrivateInputStream*.lisp")
(ld "*com.sun.cldc.io.j2me.http.Protocol$PrivateInputStream*.lisp")
(ld "*com.sun.cldc.io.j2me.http.Protocol$PrivateOutputStream*.lisp")
(ld "*com.sun.cldc.io.j2me.http.Protocol*.lisp")
(ld "*com.sun.cldc.io.j2me.resource.Protocol*.lisp")
(ld "*com.sun.cldc.io.j2me.resource.PrivateInputStream*.lisp")
(ld "*com.sun.cldc.io.j2me.serversocket.Protocol*.lisp")
(ld "*com.sun.cldc.io.j2me.socket.Protocol*.lisp")
(ld "*com.sun.cldc.io.j2me.socket.PrivateInputStream*.lisp")
(ld "*com.sun.cldc.io.j2me.socket.PrivateInputStreamWithBuffer*.lisp")
(ld "*com.sun.cldc.io.j2me.socket.PrivateOutputStream*.lisp")
(ld "*com.sun.cldc.io.j2se.UniversalFilterInputStream*.lisp")
(ld "*com.sun.cldc.util.TimeZoneImplementation*.lisp")
(ld "*com.sun.cldc.util.j2me.CalendarImpl*.lisp")
(ld "*com.sun.cldc.util.j2me.TimeZoneImpl*.lisp")
(ld "*java.lang.Object*.lisp")
(ld "*java.lang.Class*.lisp")
(ld "*java.lang.String*.lisp")
(ld "*java.lang.Exception*.lisp")
(ld "*java.lang.Throwable*.lisp")
(ld "*java.lang.StringBuffer*.lisp")
(ld "*java.lang.ClassNotFoundException*.lisp")
(ld "*java.lang.InstantiationException*.lisp")
(ld "*java.lang.IllegalAccessException*.lisp")
(ld "*java.lang.InterruptedException*.lisp")
(ld "*java.lang.Integer*.lisp")
(ld "*java.lang.NumberFormatException*.lisp")
(ld "*java.lang.IllegalArgumentException*.lisp")
(ld "*java.lang.RuntimeException*.lisp")
(ld "*java.lang.System*.lisp")
(ld "*java.lang.NullPointerException*.lisp")
(ld "*java.lang.ClassCastException*.lisp")
(ld "*java.lang.IndexOutOfBoundsException*.lisp")
(ld "*java.lang.Character*.lisp")
(ld "*java.lang.Error*.lisp")
(ld "*java.lang.StringIndexOutOfBoundsException*.lisp")
(ld "*java.lang.Math*.lisp")
(ld "*java.lang.Long*.lisp")
(ld "*java.lang.Runtime*.lisp")
(ld "*java.lang.ArrayIndexOutOfBoundsException*.lisp")
(ld "*java.lang.ArithmeticException*.lisp")
(ld "*java.lang.ArrayStoreException*.lisp")
(ld "*java.lang.Boolean*.lisp")
(ld "*java.lang.Byte*.lisp")
(ld "*java.lang.IllegalMonitorStateException*.lisp")
(ld "*java.lang.IllegalThreadStateException*.lisp")
(ld "*java.lang.NegativeArraySizeException*.lisp")
(ld "*java.lang.OutOfMemoryError*.lisp")
(ld "*java.lang.VirtualMachineError*.lisp")
(ld "*java.lang.Runnable*.lisp")
(ld "*java.lang.SecurityException*.lisp")
(ld "*java.lang.Short*.lisp")
(ld "*java.lang.Thread*.lisp")
(ld "*java.io.UnsupportedEncodingException*.lisp")
(ld "*java.io.IOException*.lisp")
(ld "*java.io.InputStream*.lisp")
(ld "*java.io.Reader*.lisp")
(ld "*java.io.OutputStream*.lisp")
(ld "*java.io.Writer*.lisp")
(ld "*java.io.PrintStream*.lisp")
(ld "*java.io.OutputStreamWriter*.lisp")
(ld "*java.io.ByteArrayInputStream*.lisp")
(ld "*java.io.ByteArrayOutputStream*.lisp")
(ld "*java.io.DataInputStream*.lisp")
(ld "*java.io.DataInput*.lisp")
(ld "*java.io.DataOutputStream*.lisp")
(ld "*java.io.DataOutput*.lisp")
(ld "*java.io.EOFException*.lisp")
(ld "*java.io.UTFDataFormatException*.lisp")
(ld "*java.io.InterruptedIOException*.lisp")
(ld "*java.util.Hashtable$HashtableEnumerator*.lisp")
(ld "*java.util.Hashtable*.lisp")
(ld "*java.util.HashtableEntry*.lisp")
(ld "*java.util.Enumeration*.lisp")
(ld "*java.util.NoSuchElementException*.lisp")
(ld "*java.util.TimeZone*.lisp")
(ld "*java.util.Calendar*.lisp")
(ld "*java.util.Date*.lisp")
(ld "*java.util.EmptyStackException*.lisp")
(ld "*java.util.Random*.lisp")
(ld "*java.util.Stack*.lisp")
(ld "*java.util.Vector*.lisp")
(ld "*java.util.VectorEnumerator*.lisp")
(ld "*javax.microedition.io.Connector*.lisp")
(ld "*javax.microedition.io.Connection*.lisp")
(ld "*javax.microedition.io.ConnectionNotFoundException*.lisp")
(ld "*javax.microedition.io.InputConnection*.lisp")
(ld "*javax.microedition.io.OutputConnection*.lisp")
(ld "*javax.microedition.io.ContentConnection*.lisp")
(ld "*javax.microedition.io.StreamConnection*.lisp")
(ld "*javax.microedition.io.Datagram*.lisp")
(ld "*javax.microedition.io.DatagramConnection*.lisp")
(ld "*javax.microedition.io.StreamConnectionNotifier*.lisp")


(defconst *.-class-table*
  (make-class-table1 
   *com.sun.cldc.i18n.StreamReader*
   *com.sun.cldc.i18n.StreamWriter*
   *com.sun.cldc.i18n.uclc.DefaultCaseConverter*
   *com.sun.cldc.i18n.Helper*
   *com.sun.cldc.i18n.j2me.ISO8859_1_Reader*
   *com.sun.cldc.i18n.j2me.ISO8859_1_Writer*
   *com.sun.cldc.i18n.j2se.Default_Writer*
   *com.sun.cldc.io.DateParser*
   *com.sun.cldc.io.ConnectionBaseInterface*
   *com.sun.cldc.io.GeneralBase*
   *com.sun.cldc.io.ConnectionBase*
   *com.sun.cldc.io.NetworkConnectionBase*
   *com.sun.cldc.io.connections.HttpConnection*
   *com.sun.cldc.io.j2me.comm.Protocol*
   *com.sun.cldc.io.j2me.comm.PrivateInputStream*
   *com.sun.cldc.io.j2me.comm.PrivateInputStreamWithBuffer*
   *com.sun.cldc.io.j2me.comm.PrivateOutputStream*
   *com.sun.cldc.io.j2me.datagram.DatagramObject*
   *com.sun.cldc.io.j2me.datagram.Protocol*
   *com.sun.cldc.io.j2me.debug.Protocol*
   *com.sun.cldc.io.j2me.debug.PrivateOutputStream*
   *com.sun.cldc.io.j2me.events.Protocol*
   *com.sun.cldc.io.j2me.events.PrivateInputStream*
   *com.sun.cldc.io.j2me.http.Protocol$PrivateInputStream*
   *com.sun.cldc.io.j2me.http.Protocol$PrivateOutputStream*
   *com.sun.cldc.io.j2me.http.Protocol*
   *com.sun.cldc.io.j2me.resource.Protocol*
   *com.sun.cldc.io.j2me.resource.PrivateInputStream*
   *com.sun.cldc.io.j2me.serversocket.Protocol*
   *com.sun.cldc.io.j2me.socket.Protocol*
   *com.sun.cldc.io.j2me.socket.PrivateInputStream*
   *com.sun.cldc.io.j2me.socket.PrivateInputStreamWithBuffer*
   *com.sun.cldc.io.j2me.socket.PrivateOutputStream*
   *com.sun.cldc.io.j2se.UniversalFilterInputStream*
   *com.sun.cldc.util.TimeZoneImplementation*
   *com.sun.cldc.util.j2me.CalendarImpl*
   *com.sun.cldc.util.j2me.TimeZoneImpl*
   *java.lang.Object*
   *java.lang.Class*
   *java.lang.String*
   *java.lang.Exception*
   *java.lang.Throwable*
   *java.lang.StringBuffer*
   *java.lang.ClassNotFoundException*
   *java.lang.InstantiationException*
   *java.lang.IllegalAccessException*
   *java.lang.InterruptedException*
   *java.lang.Integer*
   *java.lang.NumberFormatException*
   *java.lang.IllegalArgumentException*
   *java.lang.RuntimeException*
   *java.lang.System*
   *java.lang.NullPointerException*
   *java.lang.ClassCastException*
   *java.lang.IndexOutOfBoundsException*
   *java.lang.Character*
   *java.lang.Error*
   *java.lang.StringIndexOutOfBoundsException*
   *java.lang.Math*
   *java.lang.Long*
   *java.lang.Runtime*
   *java.lang.ArrayIndexOutOfBoundsException*
   *java.lang.ArithmeticException*
   *java.lang.ArrayStoreException*
   *java.lang.Boolean*
   *java.lang.Byte*
   *java.lang.IllegalMonitorStateException*
   *java.lang.IllegalThreadStateException*
   *java.lang.NegativeArraySizeException*
   *java.lang.OutOfMemoryError*
   *java.lang.VirtualMachineError*
   *java.lang.Runnable*
   *java.lang.SecurityException*
   *java.lang.Short*
   *java.lang.Thread*
   *java.io.UnsupportedEncodingException*
   *java.io.IOException*
   *java.io.InputStream*
   *java.io.Reader*
   *java.io.OutputStream*
   *java.io.Writer*
   *java.io.PrintStream*
   *java.io.OutputStreamWriter*
   *java.io.ByteArrayInputStream*
   *java.io.ByteArrayOutputStream*
   *java.io.DataInputStream*
   *java.io.DataInput*
   *java.io.DataOutputStream*
   *java.io.DataOutput*
   *java.io.EOFException*
   *java.io.UTFDataFormatException*
   *java.io.InterruptedIOException*
   *java.util.Hashtable$HashtableEnumerator*
   *java.util.Hashtable*
   *java.util.HashtableEntry*
   *java.util.Enumeration*
   *java.util.NoSuchElementException*
   *java.util.TimeZone*
   *java.util.Calendar*
   *java.util.Date*
   *java.util.EmptyStackException*
   *java.util.Random*
   *java.util.Stack*
   *java.util.Vector*
   *java.util.VectorEnumerator*
   *javax.microedition.io.Connector*
   *javax.microedition.io.Connection*
   *javax.microedition.io.ConnectionNotFoundException*
   *javax.microedition.io.InputConnection*
   *javax.microedition.io.OutputConnection*
   *javax.microedition.io.ContentConnection*
   *javax.microedition.io.StreamConnection*
   *javax.microedition.io.Datagram*
   *javax.microedition.io.DatagramConnection*
   *javax.microedition.io.StreamConnectionNotifier*))



